---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: echoenv
  name: echoenv
spec:
  ports:
  - name: 8080-tcp
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: echoenv
  sessionAffinity: None
  type: ClusterIP

