---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: echoenv
  name: echoenv
spec:
  port:
    targetPort: 8080-tcp
  to:
    kind: Service
    name: echoenv
    weight: 100
  wildcardPolicy: None

