---
apiVersion: config.openshift.io/v1
kind: Ingress
metadata:
  name: cluster
spec:
  domain: apps.skrenger-gitops.sandbox810.opentlc.com
  loadBalancer:
    platform:
      aws:
        type: Classic
      type: AWS
