apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-app
spec:
  destination:
    namespace: fitam01-project
    server: https://kubernetes.default.svc 
  project: default 
  source: 
    path: demo-01/manifests
    repoURL: https://github.com/przlod/gitops-fi.git
    targetRevision: main
  syncPolicy: 
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - ServerSideApply=true
