apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: echoenv-app
spec:
  destination:
    namespace: simon01-project
    server: https://kubernetes.default.svc 
  project: default 
  source: 
    path: demo-01/manifests
    repoURL: https://github.com/simonkrenger/gitops-basics-demos.git
    targetRevision: main
  syncPolicy: 
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - ServerSideApply=true
