---
apiVersion: operator.openshift.io/v1
kind: InsightsOperator
metadata:
  annotations:
    capability.openshift.io/name: Insights
    include.release.openshift.io/ibm-cloud-managed: 'true'
    include.release.openshift.io/self-managed-high-availability: 'true'
    include.release.openshift.io/single-node-developer: 'true'
  name: cluster
spec:
  logLevel: Normal
  managementState: Managed
  operatorLogLevel: Normal
