apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: application-1
  namespace: openshift-gitops
spec:
  destination:
    namespace: application-1
    server: "https://kubernetes.default.svc"
  source:
    repoURL: "https://github.com/przlod/gitops-fi.git"
    path: "demo-03/application-1/"
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
