apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: application-2
  namespace: openshift-gitops
spec:
  destination:
    namespace: application-2
    server: "https://kubernetes.default.svc"
  source:
    repoURL: "https://github.com/simonkrenger/gitops-basics-demos.git"
    path: "demo-03/application-2/"
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
