apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: insights
spec:
  destination:
    namespace: openshift-gitops
    server: https://kubernetes.default.svc 
  project: default 
  source: 
    path: demo-02/insightsoperator
    repoURL: https://github.com/simonkrenger/gitops-basics-demos.git
    targetRevision: main
  syncPolicy: 
    automated:
      selfHeal: true
    syncOptions:
    - ServerSideApply=true
